### ISSUE TITLE
请问七牛云怎么配置

### ISSUE THREAD

**Issue by hiifong** [eleven26/goss#10]
我的配置如下,
![image](https://github.com/eleven26/goss/assets/89133723/362161d6-7c30-4162-ba2a-d6d14a119fe1)
![image](https://github.com/eleven26/goss/assets/89133723/14085edf-9059-41b3-9680-71f03f38aa70)

**Comment by eleven26** [comment]
域名应该有问题，可以参考这个 https://developer.qiniu.com/kodo/4088/s3-access-domainname

**Comment by hiifong** [comment]
谢谢
